name: Release

on:
  push:
    branches:
      - main
      - pre-release # branche de pré-production

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Pour créer des tags et releases
      issues: write     # Pour commenter les issues liées
      pull-requests: write # Pour commenter les PR liées
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # Important : semantic-release a besoin de tout l'historique

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        # On utilise "npm install" si pas de package-lock.json, 
        # sinon "npm ci" est préférable.
        run: |
          npm install @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release